openapi: 3.1.0
info:
  title: PIN Management System API v1
  description: |
    PIN Management System API is added as part of Verified Delivery that will offer shippers extra security to ensure the package is delivered to the intended recipient. A secure PIN will be required to release the package for delivery. 
  version: "1.0"
tags:
  - name: tokens
    description: "A Public API which handles operations related to creating a token"
  - name: pins
    description: "Operations related to retrieving a PIN by token and retrieving PINs for the list of tracking numbers"
  - name: epra
    description: "Operations related to retrieving the EPRA release code and related actions for a given tracking number"
servers:
  - url: https://onlinetools.ups.com/api/pin-mgmt-sys/{version}
    description: external url for PIN Management System
    variables:
      version:
        description: API version
        default: v1
        enum: 
          - v1
paths:
  /pins/token:
    post:
      tags:
        - Protected Delivery Token
      operationId: generateToken
      summary: Generate Token
      description: |
        This endpoint is used to generate a token using Shipper generated PIN
      parameters:
        - $ref: '#/components/parameters/transID'
        - $ref: '#/components/parameters/transactionSrc'
      security:
        - OAuth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateTokenRequest'
            example:
              pin: "123456"
      responses:
        '200':
          description: Token is generated successfully
          headers:
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateTokenResponse'
              example: 
                token: "550e8400-e29b-41d4-a716-446655440000"
        '400':
          description: "Missing required values or incorrect values or validation fails"
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing pin:
                  value:
                    errors:
                      - code: "50001"
                        message: "Pin is required for request"
        '401':
          description: Unauthorized
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  value:
                    errors:
                      - code: "250002"
                        message: "Invalid Authentication Information"
        '403':
          description: Forbidden
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  value:
                    errors:
                      - code: "40301"
                        message: "You do not have permission to access this resource."
        '404':
          description: Not Found
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NotFound:
                  value:
                    errors:
                      - code: "40401"
                        message: "The specified resource was not found."
        '415':
          description: Unsupported Media Type
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UnsupportedMediaType:
                  value:
                    errors:
                      - code: "41501"
                        message: "The server cannot process the request because the payload format is not supported."
        '429':
          description: Too Many Requests
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TooManyRequests:
                  value:
                    errors:
                      - code: "42901"
                        message: "You have sent too many requests in a short period. Please try again later."
        '500':
          description: Internal Server Error
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InternalServerError:
                  value:
                    errors:
                      - code: "10067"
                        message: "Internal Server Error"
  
    get:
      tags:
        - Protected Delivery Token
      operationId: getPinByToken
      summary: Get Pin by Token
      description: |
        This endpoint is used to get Pin by Token.
      parameters:
        - name: X-UserToken
          in: header
          required: true
          description: Token generated by Generate Token API
          schema:
            type: string
            format: uuid
        - $ref: '#/components/parameters/transID'
        - $ref: '#/components/parameters/transactionSrc'
      security:
        - OAuth2: []
      responses:
        '200':
          description: Pin is returned successfully
          headers:
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPinByTokenResponse'
              example: 
                pin: "123456"
        '400':
          description: "Missing required values or incorrect values or validation fails"
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing Required Value:
                  value:
                    errors:
                      - code: "50001"
                        message: "Token is required for request"
        '401':
          description: Unauthorized
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  value:
                    errors:
                      - code: "250002"
                        message: "Invalid Authentication Information"
        '403':
          description: Forbidden
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  value:
                    errors:
                      - code: "40301"
                        message: "You do not have permission to access this resource."
        '404':
          description: Not Found
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NotFound:
                  value:
                    errors:
                      - code: "40401"
                        message: "The specified resource was not found."
        '429':
          description: Too Many Requests
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TooManyRequests:
                  value:
                    errors:
                      - code: "42901"
                        message: "You have sent too many requests in a short period. Please try again later."
        '500':
          description: Internal Server Error
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InternalServerError:
                  value:
                    errors:
                      - code: "10067"
                        message: "Internal Server Error"
  /pins/retrieve:
    post:
      tags:
        - Protected Delivery Token
      operationId: getPinsForTrackingNumberList
      summary: Get Pins for the list of Tracking Numbers
      description: |
        This endpoint is used to get Pins for the list of Tracking Numbers.
      parameters:
        - $ref: '#/components/parameters/transID'
        - $ref: '#/components/parameters/transactionSrc'
      security:
        - OAuth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetPinsForTrackingNumberListRequest'
            example:
              trackingNumbers: ["1Z999AA10123456784","1Z999AA10123456785","1Z999AA10123456786"]
      responses:
        '200':
          description: Pins are returned successfully
          headers:
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPinsForTrackingNumberListResponse'
              example:
                results: 
                  - trackingNumber: "1Z999AA10123456784"
                    pin: "123456"
                  - trackingNumber: "1Z999AA10123456785"
                    pin: "005678"
        '400':
          description: "Missing required values or incorrect values or validation fails"
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing Required Value:
                  value:
                    errors:
                      - code: "50001"
                        message: "Tracking Numbers are required for request"
        '401':
          description: Unauthorized
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  value:
                    errors:
                      - code: "250002"
                        message: "Invalid Authentication Information"
        '403':
          description: Forbidden
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  value:
                    errors:
                      - code: "40301"
                        message: "You do not have permission to access this resource."
        '404':
          description: Not Found
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NotFound:
                  value:
                    errors:
                      - code: "40401"
                        message: "The specified resource was not found."
        '415':
          description: Unsupported Media Type
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                UnsupportedMediaType:
                  value:
                    errors:
                      - code: "41501"
                        message: "The server cannot process the request because the payload format is not supported."
        '429':
          description: Too Many Requests
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TooManyRequests:
                  value:
                    errors:
                      - code: "42901"
                        message: "You have sent too many requests in a short period. Please try again later."
        '500':
          description: Internal Server Error
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InternalServerError:
                  value:
                    errors:
                      - code: "10067"
                        message: "Internal Server Error"
  /pins/epra:
    get:
      tags:
        - Protected Delivery Token
      operationId: getEPRACodeAndActions
      summary: Get EPRA (Electronic Package Release Authentication) release code and related actions
      description: |
        This endpoint retrieves the EPRA release code and related actions for a given tracking number. The EPRA release code is used to determine the necessary steps for package release in the Verified Delivery process.
      security:
        - OAuth2: []
      parameters:
        - name: action
          in: query
          required: false
          schema:
            type: string
        - name: trackingNumber
          in: header
          required: true
          schema:
            type: string
        - name: epra
          in: header
          required: false
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/transID'
        - $ref: '#/components/parameters/transactionSrc'
      responses:
        '200':
          description: EPRA response.
          headers:
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpraResponse'
              example: 
                response:
                  epraCode: "EPRA123"
                  epraRequired: "Yes"
                  epraMatch: "No"
                  epraKiala: "N/A"
        '400':
          description: Invalid request.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing required header(s) in request:
                  value:
                    errors:
                      - code: "10013"
                        message: "Missing required header(s) in request"
        '401':
          description: Unauthorized.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Invalid Token:
                  value:
                    errors:
                      - code: "250002"
                        message: "Invalid Authentication Information"
        '403':
          description: Forbidden.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  value:
                    errors:
                      - code: "40301"
                        message: "You do not have permission to access this resource."
        '404':
          description: EPRA or tracking record not found.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NotFound:
                  value:
                    errors:
                      - code: "40401"
                        message: "The specified resource was not found."
        '429':
          description: Too many requests.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TooManyRequests:
                  value:
                    errors:
                      - code: "42901"
                        message: "You have sent too many requests in a short period. Please try again later."
        '500':
          description: Internal error.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                SQL exception experienced:
                  value:
                    errors:
                      - code: "90401"
                        message: "SQL exception experienced"
        '501':
          description: EPRA service not implemented.
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Not Implemented:
                  value:
                    errors:
                      - code: "10068"
                        message: "The webservice is disabled"
components:
  parameters:
    transID:
      name: transID
      in: header
      required: true
      description: Transaction ID
      schema:
        type: string
    transactionSrc:
      name: transactionSrc
      in: header
      required: true
      description: Transaction Source
      schema:
        type: string
  headers:
    BkndTransId:
      description: The backend uuid transaction id.
      schema:
        type: string
    transactionSrc:
      description: Identifies the client/source application that is calling.
      schema:
        type: string
    APIErrorCode:
      description: The API error code.
      schema:
        type: string
    APIErrorMsg:
      description: The API error message
      schema:
        type: string
  schemas:
    GenerateTokenRequest:
      type: object
      properties:
        pin:
          type: string
          pattern: '^[0-9]{4,6}$'
          minLength: 4
          maxLength: 6
          description: The Pin for which the token is generated (4 to 6 digits, leading zeros allowed; e.g., 0007).
      required:
        - pin
      description: 'This request is sent to generate a token for a given Pin.'
      title: GenerateTokenRequest
    GenerateTokenResponse:
      type: object
      properties:        
        token:
          type: string
          description: The generated token for the given Pin.
      required:
        - token
      description: 'This response returns the generated token for the given Pin.'
      title: GenerateTokenResponse
    GetPinByTokenResponse:
      type: object
      properties:
        pin:
          type: string
          pattern: '^[0-9]{4,6}$'
          minLength: 4
          maxLength: 6
          description: The Pin associated with the given token (4 to 6 digits, leading zeros allowed; e.g., 0007).
      required:
        - pin
      description: 'This response returns the Pin associated with the given token.'
      title: GetPinByTokenResponse
    GetPinsForTrackingNumberListRequest:
      type: object
      properties:
        trackingNumbers:
          type: array
          maxItems: 100
          minItems: 1
          items:
              type: string
              pattern: '^1Z[A-Z0-9]{16}$'
              description: Tracking number
          description: A list of tracking numbers for which the Pins are requested.
      required:
        - trackingNumbers
      description: 'This request is sent to retrieve Pins for a list of tracking numbers.'
      title: GetPinsForTrackingNumberListRequest
    GetPinsForTrackingNumberListResponse:
      type: object
      properties:
        results:
          type: array
          minItems: 1
          items:
            type: object
            properties:
              trackingNumber:
                type: string
                pattern: '^1Z[A-Z0-9]{16}$'
                description: The tracking number associated with the Pin.
              pin:
                type: string
                pattern: '^[0-9]{4,6}$'
                minLength: 4
                maxLength: 6
                description: The Pin associated with the given tracking number (4 to 6 digits, leading zeros allowed; e.g., 0007).
            required:
              - trackingNumber
              - pin
      required:
        - results
      description: 'This response returns a list of tracking numbers and their associated Pins.'
      title: GetPinsForTrackingNumberListResponse
    EpraResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/EpraElement'
      required: [response]
      description: 'This response returns the EPRA release code and related actions for a given tracking number.'
      title: EpraResponse
    EpraElement:
      type: object
      properties:
        epraCode:
          type: string
        epraRequired:
          type: string
        epraMatch:
          type: string
        epraKiala:
          type: string
    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Error'
          description: "Standardized error object for responses and callbacks."
      description: 'This response is returned when an error occurs, containing a list of error objects with standardized error codes and messages.'
      title: ErrorResponse
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: "Error code"
        message:
          type: string
          description: "Human-readable error message providing additional context about the error."
      description: 'This object represents an error, containing a standardized error code and a human-readable message.'
      title: Error
    WarningResponse:
      type: object
      properties:
        response:
          $ref: '#/components/schemas/Warning'
      required: [response]
      description: 'This response returns warnings related to the request.'
      title: WarningResponse
    Warning:  
      type: object
      properties:
        code:
          type: string
          description: "Warning code"
        message:
          type: string
          description: "Human-readable warning message providing additional context about the warning."
      description: 'This object represents a warning, containing a standardized warning code and a human-readable message.'
      title: Warning
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          x-tokenEndpointAuthMethod: client_secret_basic
          tokenUrl: https://onlinetools.ups.com/security/v1/oauth/token
          scopes: {}
