openapi: 3.1.0
info: 
  title: WorldEase Shipment Management API v2205
  description: |
    The WorldEase Shipment Management API facilitates the consolidation of packages into a single shipment. It offers users
    the ability to manage the shipment lifecycle including aggregating individual packages, closing out shipments once
    consolidation is completed and managing master and child shipments with options to delete as necessary.

    **Key Business Values**
    - reduces brokerage fees
    - streamlines the international shipping process
    <p>Explore API documentation and sample applications through GitHub.</p>
  
    <a href="https://github.com/UPS-API" target="_blank" rel="noopener noreferrer">
    <img src="https://www.ups.com/assets/resources/webcontent/images/gitHubButton.svg" alt="Open in GitHub" style="width: 128px; height: 32px;">
    </a>	
  version: "1.0"
tags:
  - name: World Ease Shipment Management - Shipment
    description: For endpoint that allows user to finalize the close out shipments
  - name: Shipment Modification 
    description: For endpoints that allow deletion of master and child shipments
servers:
  - url: Not Available
    description: Customer Integration Environment
  - url: "https://onlinetools.ups.com/api/ship/{version}"
    description: Production
    variables:
      version: 
        description: Denotes which version of the API to be called as new features are released.
        default: v2205
        enum:  
           - v2205 
paths:
  /master-shipment/closeout/{shipment_gccn}:
    post:
      tags:
        - World Ease Shipment Management - Shipment
      operationId: saveCloseOutShipment
      summary: Closeout the shipment saving the WorldEase summary label to the database
      description: |
        Finalizes the shipment process by marking a package or set of packages as ready for dispatch, effectively ending
        the consolidation stage.
      parameters:
        - $ref: "#/components/parameters/transId"
        - $ref: "#/components/parameters/transactionSrc"
        - $ref: "#/components/parameters/shipment_gccn"
      security:
        - oauth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloseoutRequest'
            examples:
              CloseOutRequest:
                summary: Close the Master Shipment
                value:
                  shipperAccountNumber: ISUS01
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloseoutResponse'
              examples:
                CloseOutResponse:
                  value:
                    transId: 4ce27ff5-8e17-4797-a8c1-089796db
                    label: 
                       opTyp: PNG
                       lblNmbr: MVpJU1VTMDE2NzIzODc4Mjc3
                       lblData: asdfhkjuiovrtyuiopfghjkxcv
        '400':
          description: Bad Request
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BadGCCNExample:
                  summary: Missing GCCN
                  value:
                    errors:
                      - code: "20007"
                        message: Missing GCCN        
        '401':
            description: Unauthorized
            content: 
              application/json: 
                schema: 
                  $ref: "#/components/schemas/ErrorResponse"
                examples:
                  Invalid Token:
                    summary: Invalid Token
                    value:
                      errors:
                        - code: "250002"
                          message: Invalid Authentication Information
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                GCCNNotFound:
                  summary: GCCN Not Found
                  value:
                    errors:
                      -  code: "20008"
                         message: GCCN Not Found
                AccountNumberNotFound:
                  summary: Account Number Not Found
                  value:
                    errors:
                      - code: "20008"
                        message: Shipper Account Number Not Found
  /master-shipment/{shipment_gccn}:
    delete:
      tags:
        - World Ease Shipment Management - Shipment
      operationId: deleteMasterShipment
      summary: Deletes the master shipment
      description: Deletes the specified master shipment from the system. Once deleted system cannot be recovered
      parameters:
        - $ref: "#/components/parameters/transId"
        - $ref: "#/components/parameters/transactionSrc"
        - $ref: "#/components/parameters/shipment_gccn"
      security:
        - oauth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteMasterShipmentRequest'
            examples:
              DeleteRequest:
                summary: Delete the Master Shipment
                value:
                  shipperAccountNumber: ISUS01
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
              examples:
                Success:
                  value:
                    code: "1"
                    message: The Delete request has been done successfully for the following GCCN - 12345678901
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BadGCCNExample:
                  summary: Missing GCCN
                  value:
                    errors:
                      - code: "20007"
                        message: Missing GCCN
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  summary: Invalid Token
                  value:
                    errors:
                      - code: "250002"
                        message: Invalid Authentication Information
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                GCCNNotFound:
                  summary: GCCN Not Found
                  value:
                    errors:
                      -  code: "20008"
                         message: GCCN Not Found
                AccountNumberNotFound:
                  summary: Account Number Not Found
                  value:
                    errors:
                      - code: "20008"
                        message: Shipper Account Number Not Found
  /child-shipment/{shipment_gccn}/{tracking_number}:
    delete:
      tags:
        - World Ease Shipment Management - Shipment
      operationId: deleteChildShipment
      summary: Delete the child shipment
      description: This is used to delete the child shipment record from the database
      parameters:
        - $ref: "#/components/parameters/transId"
        - $ref: "#/components/parameters/transactionSrc"
        - $ref: "#/components/parameters/shipment_gccn"
        - name: tracking_number
          in: path
          required: true
          description: The identifier of the shipment to identify the child shipment. It is also known as 1Z Tracking Number.
          schema:
            type: string
            pattern: ^1Z[0-9A-Z]{16}$
            example: 1ZFW10R90394837503
      security:
        - oauth2: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
              examples:
                WeDeleteResponseSummary:
                  value:
                    code: "1"
                    message: The Delete request has been done successfully for the following 1Z tracking Number- 1Z9991450419000046
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                BadGCCNExample:
                  summary: Missing GCCN
                  value:
                    errors:
                      - code: "20007"
                        message: Missing GCCN
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  summary: Invalid Token
                  value:
                    errors:
                      - code: "250002"
                        message: Invalid Authentication Information
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                GCCNNotFound:
                  summary: GCCN Not Found
                  value:
                    errors:
                      - code: "20008"
                        message: GCCN Not Found
                TrackingNumberNotFound:
                  summary: Tracking Number Not Found
                  value:
                    errors:
                      -  code: "20008"
                         message: 1Z Tracking Number Not Found
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: |
        Find your Client ID and Secret on your app info page. 
          1. Select "Try It" 
          2. In the Security section enter your Client ID and Secret 
          3. Select "Request Token"
          4. Enter any additional information in the Body and Parameters sections
          5. Select "Send" to execute your API request"
      flows:
        clientCredentials:
          x-tokenEndpointAuthMethod: client_secret_basic
          tokenUrl: https://onlinetools.ups.com/security/v1/oauth/token
          scopes: {}
  parameters:
    transId:
      name: transId
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/CustomTransactionId"
    transactionSrc:
      name: transactionSrc
      in: header
      required: true
      schema:
        description: An identifier of the client/source application that is making the request.Length 512
        type: string
        maxLength: 512
        example: SAM
    shipment_gccn:
      name: shipment_gccn
      in: path
      required: true
      description: The unique identifier of the shipment to close Out. It also known as GCCN.
      schema:
        $ref: '#/components/schemas/GCCN'
  schemas:
    CloseoutRequest:
      type: object
      required:
        - shipperAccountNumber
      properties:
        shipperAccountNumber:
          $ref: '#/components/schemas/AccountNumber'
      additionalProperties: false
    CloseoutResponse:
      type: object
      required:
        - transId
        - label
      properties:
        transId:
          $ref: "#/components/schemas/CustomTransactionId"
        label:
          type:  object
          description: This will contain master shipment label
          required:
            - opTyp
            - lblNmbr
            - lblData
          properties:
            opTyp:
              $ref: '#/components/schemas/DocumentFormat'
            lblNmbr:
              type: string
              description: The label number assigned to this label
              example: MVpJU1VTMDE2NzIzODc4Mjc3
            lblData:
              type: string
              description: Base64 encoded label image
              example: asdfhkjuiovrtyuiopfghjkxcv
          additionalProperties: false
        physicalDocBoxLabel:
          type: object
          description: This object will only be returned if at time of Shipment creation masterHasDocBox element is set to 1.
          required:
            - opTyp
            - lblNmbr
            - lblData
          properties:
            opTyp:
              $ref: '#/components/schemas/DocumentFormat'
            lblNmbr:
              type: string
              description: The label number assigned to this label
              example: MVo3ODMzWVk2NzM0MjA2MTI3
            lblData:
              type: string
              description: Base64 encoded label image
              example: RGF0ZSAoRDoyMDI2MDcxNzEzNDAzNCswMCcwMCcpPj4KZW5kb2JqCjMgMCBvYmoKPDwvY2EgMQ
          additionalProperties: false
      additionalProperties: false
    DeleteMasterShipmentRequest:
      type: object
      required:
        - shipperAccountNumber
      properties:
        shipperAccountNumber:
          $ref: '#/components/schemas/AccountNumber'
      additionalProperties: false
    DeleteResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Identifies the success or failure of the transaction.
          oneOf:
            - title: Successful
              const: "1"
        message:
          type: string
          description: Succesful text message
      additionalProperties: false

    #COMMON
    AccountNumber:
      type: string
      description: The unique account number associated with the Shipper. It is also known as UPS Shipper Account Number.
      pattern: ^[A-Z0-9]{6}$
      example: "1213YY"
    CustomTransactionId:
      description: Client generated id which is treated as the Transaction ID
      type: string
      minLength: 32
      maxLength: 32
      pattern: '^[a-fA-F0-9\-]+$'
      example:
        4ce27ff5-8e17-4797-a8c1-089796db
    DocumentFormat:
      type: string
      description: The format of the document.
      oneOf:
        - title: Portable Document Format
          description: Must be used for Consolidated Invoice (CI)
          const: PDF
        - title: Portable Network Graphic
          const: PNG
        - title: Graphics Interchange Format
          const: GIF
        - title: Zebra Programming Language
          const: ZPL
        - title: Eltron Programming Lanaguage
          const: EPL
        - title: Star Micronics Printer Language
          const: STARPL
        - title: Samsung Printer Language
          const: SPL
        - title: JavaScript Object Notation
          description: Must be used for World Ease Movement Summary Label (WESL)
          const: JSON
    ErrorResponse:
      description: Error response entity
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: error payload - array containing one or more Errors
          items:
            type: object
            properties:
              code:
                type: string
                description: The code is specific to the error.
              message:
                type: string
                description: The message that associated with the above error code.
    GCCN:
      type: string
      description: The unique Global Customer Consolidation Number representing the master shipment
      maxLength: 11
      pattern: ^[A-Z0-9]{11}$
      example: 5597YY9TM9V